// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3b3CrNP4Iz-sPwHQ6nTRQy_4oFowG_28',
    appId: '1:55640729376:web:f82c29af2d855b8eb35945',
    messagingSenderId: '55640729376',
    projectId: 'fir-4-3de7e',
    authDomain: 'fir-4-3de7e.firebaseapp.com',
    storageBucket: 'fir-4-3de7e.appspot.com',
    measurementId: 'G-1NRFFJ00FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEuqVaQMdD57Fnk8iUrH_1l3a4znUtU1k',
    appId: '1:55640729376:android:354eb0cd1596df9ab35945',
    messagingSenderId: '55640729376',
    projectId: 'fir-4-3de7e',
    storageBucket: 'fir-4-3de7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIll0X0u_dEtPD8-KkJmKmI52q_Mgv5fA',
    appId: '1:55640729376:ios:9b2bb3bc04362cd5b35945',
    messagingSenderId: '55640729376',
    projectId: 'fir-4-3de7e',
    storageBucket: 'fir-4-3de7e.appspot.com',
    iosBundleId: 'com.example.firebase4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIll0X0u_dEtPD8-KkJmKmI52q_Mgv5fA',
    appId: '1:55640729376:ios:9b2bb3bc04362cd5b35945',
    messagingSenderId: '55640729376',
    projectId: 'fir-4-3de7e',
    storageBucket: 'fir-4-3de7e.appspot.com',
    iosBundleId: 'com.example.firebase4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3b3CrNP4Iz-sPwHQ6nTRQy_4oFowG_28',
    appId: '1:55640729376:web:4288e973a0d57eb4b35945',
    messagingSenderId: '55640729376',
    projectId: 'fir-4-3de7e',
    authDomain: 'fir-4-3de7e.firebaseapp.com',
    storageBucket: 'fir-4-3de7e.appspot.com',
    measurementId: 'G-FYQ1KP5VFC',
  );
}
